# Generated by Django 5.0.1 on 2024-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0018_workrecordfinally_status_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workrecordfinally',
            options={'ordering': ['date', 'person']},
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='status',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
