# Generated by Django 5.0.1 on 2024-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0019_alter_workrecordfinally_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecordfinally',
            name='status_accept_overtime',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workrecordfinally',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
