# Generated by Django 5.0.1 on 2024-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0020_workrecordfinally_status_accept_overtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecordfinally',
            name='status_day_off',
            field=models.SmallIntegerField(default=1, null=True),
        ),
    ]
