# Generated by Django 5.0.1 on 2024-05-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0021_workrecordfinally_status_day_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecordfinally',
            name='weekday_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
