# Generated by Django 5.0.1 on 2025-01-29 10:53

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0022_workrecordfinally_weekday_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('A', 'غایت'), ('P', 'حاضر'), ('O', 'مرخضی'), ('M', 'ماموریت')], default='P', max_length=10),
        ),
        migrations.CreateModel(
            name='WorkRecordDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_work', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('arrived_time', models.TimeField(blank=True, null=True, verbose_name='ساعت ورود')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='ساعت خروج')),
                ('status', models.CharField(choices=[('A', 'غایت'), ('P', 'حاضر'), ('O', 'مرخضی'), ('M', 'ماموریت')], default='P', max_length=10, verbose_name='وضعیت روزانه کارمند')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'ثبت کارکرد روزانه',
                'verbose_name_plural': 'ثبت کارکرد های روزانه',
                'ordering': ['date_work', 'person'],
            },
        ),
    ]
