# Generated by Django 5.0.1 on 2025-01-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0023_alter_workrecord_status_workrecorddaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('A', 'غایت'), ('P', 'حاضر'), ('O', 'مرخصی'), ('M', 'ماموریت')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='workrecorddaily',
            name='status',
            field=models.CharField(choices=[('A', 'غایت'), ('P', 'حاضر'), ('O', 'مرخصی'), ('M', 'ماموریت')], default='P', max_length=10, verbose_name='وضعیت روزانه کارمند'),
        ),
    ]
