# Generated by Django 5.0.1 on 2025-01-29 11:46

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0024_alter_workrecord_status_alter_workrecorddaily_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecorddaily',
            name='date_work',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ'),
        ),
    ]
