# Generated by Django 5.0.1 on 2025-01-29 15:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0025_alter_workrecorddaily_date_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecorddaily',
            name='date_work',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
    ]
