# Generated by Django 5.0.1 on 2025-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0026_alter_workrecorddaily_date_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('A', 'غایب'), ('P', 'حاضر'), ('O', 'مرخصی'), ('M', 'ماموریت')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='workrecorddaily',
            name='status',
            field=models.CharField(choices=[('A', 'غایب'), ('P', 'حاضر'), ('O', 'مرخصی'), ('M', 'ماموریت')], default='P', max_length=10, verbose_name='وضعیت روزانه کارمند'),
        ),
    ]
