# Generated by Django 5.0.1 on 2025-02-03 15:21

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0027_alter_workrecord_status_alter_workrecorddaily_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecorddaily',
            name='date_work',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today, verbose_name='تاریخ'),
        ),
    ]
