# Generated by Django 5.0.1 on 2025-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0028_alter_workrecorddaily_date_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrecorddaily',
            name='approval_status',
            field=models.TextField(blank=True, null=True, verbose_name='وضعیت تأیید'),
        ),
        migrations.AddField(
            model_name='workrecorddaily',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('A', 'غایب'), ('P', 'حاضر'), ('O', 'مرخصی'), ('M', 'ماموریت'), ('S', 'استعلاجی')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='workrecorddaily',
            name='status',
            field=models.CharField(choices=[('A', 'غایب'), ('P', 'حاضر'), ('O', 'مرخصی'), ('M', 'ماموریت'), ('S', 'استعلاجی')], default='P', max_length=10, verbose_name='وضعیت روزانه کارمند'),
        ),
    ]
