# Generated by Django 5.0.1 on 2025-02-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktime', '0029_workrecorddaily_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='status',
            field=models.CharField(choices=[('A', 'غایب'), ('P', 'حاضر'), ('DO', 'مرخصی روزانه'), ('HO', 'مرخصی ساعتی'), ('M', 'ماموریت'), ('S', 'استعلاجی')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='workrecorddaily',
            name='status',
            field=models.CharField(choices=[('A', 'غایب'), ('P', 'حاضر'), ('DO', 'مرخصی روزانه'), ('HO', 'مرخصی ساعتی'), ('M', 'ماموریت'), ('S', 'استعلاجی')], default='P', max_length=10, verbose_name='وضعیت روزانه کارمند'),
        ),
    ]
