# Generated by Django 5.0.1 on 2025-01-21 12:55

import django.db.models.deletion
import django_jalali.db.models
import persons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
                ('identity_number', models.CharField(max_length=20, verbose_name='شماره شناسنامه')),
                ('national_card_file', models.FileField(upload_to='documents/national_card/', validators=[persons.models.validate_file_extension], verbose_name='تصویر یا فایل کارت ملی')),
                ('birth_date', django_jalali.db.models.jDateField(verbose_name='تاریخ تولد')),
                ('identity_card_file', models.FileField(upload_to='documents/identity_card/', validators=[persons.models.validate_file_extension], verbose_name='تصویر یا فایل شناسنامه')),
                ('insurance_number', models.CharField(max_length=20, verbose_name='شماره بیمه')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='documents/profile_images/', verbose_name='عکس پرسنلی')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='EducationalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='documents/educational/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر مدرک تحصیلی')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educational_documents', to='persons.personnel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'مدرک تحصیلی',
                'verbose_name_plural': 'مدارک تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='documents/training/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر گواهینامه آموزشی')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_certificates', to='persons.personnel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'گواهینامه آموزشی',
                'verbose_name_plural': 'گواهینامه\u200cهای آموزشی',
            },
        ),
    ]
