# Generated by Django 5.0.1 on 2025-01-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_educationaldocument_name_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='number_of_children',
            field=models.IntegerField(default=0, verbose_name='تعداد فرزند'),
            preserve_default=False,
        ),
    ]
