# Generated by Django 5.0.1 on 2025-01-25 10:00

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
import persons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_personnel_number_of_children'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='educationaldocument',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationaldocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='educationaldocument',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='educationaldocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='Insurance_records',
            field=models.IntegerField(default=0, verbose_name='مجموع سوابق بیمه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='address',
            field=models.CharField(default=0, max_length=50, unique=True, verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='callphone',
            field=models.CharField(default=0, max_length=50, unique=True, verbose_name='تلفن همراه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='education_level',
            field=models.CharField(default=0, max_length=50, verbose_name='میزان تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='home_owner',
            field=models.BooleanField(default=True, verbose_name='نوع تملک'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='phone_number',
            field=models.CharField(default=0, max_length=50, unique=True, verbose_name='تلفن ثابت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی\u200cکننده'),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AddField(
            model_name='trainingcertificate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی\u200cکننده'),
        ),
        migrations.CreateModel(
            name='InsuranceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name_doc', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع سابقه بیمه')),
                ('certificate_file', models.FileField(upload_to='documents/training/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر  سابقه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_records', to='persons.personnel', verbose_name='پرسنل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی\u200cکننده')),
            ],
            options={
                'verbose_name': 'سابقه بیمه',
                'verbose_name_plural': 'سوابق بیمه',
            },
        ),
    ]
