# Generated by Django 5.0.1 on 2025-01-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_educationaldocument_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='home_owner',
        ),
    ]
