# Generated by Django 5.0.1 on 2025-01-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_remove_personnel_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='education_level',
            field=models.CharField(choices=[('cycle', 'سیکل'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('doctorate', 'دکترا'), ('postdoctorate', 'فوق دکترا'), ('seminary', 'مدارک حوزوی')], default='diploma', max_length=50, verbose_name='میزان تحصیلی'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='home_owner',
            field=models.CharField(choices=[('owner', 'مالک'), ('renter', 'مستاجر'), ('family_home', 'خانه پدری')], default='owner', max_length=20, verbose_name='نوع تملک'),
        ),
    ]
