# Generated by Django 5.0.1 on 2025-01-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_personnel_father_name_personnel_hair_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='birth_place',
            field=models.CharField(default=0, max_length=100, verbose_name='محل تولد'),
            preserve_default=False,
        ),
    ]
