# Generated by Django 5.0.1 on 2025-01-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_personnel_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='employment_status',
            field=models.CharField(choices=[('full_time', 'تمام وقت'), ('part_time', 'پاره وقت'), ('hourly', 'ساعتی'), ('consultant', 'مشاور'), ('terminated', 'قطع همکاری')], default='full_time', max_length=20, verbose_name='وضعیت کارمند'),
        ),
    ]
