# Generated by Django 5.0.1 on 2025-01-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_personnel_birth_certificate_issue_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='birth_place',
        ),
    ]
