# Generated by Django 5.0.1 on 2025-01-25 11:09

import django.db.models.deletion
import iranian_cities.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0009_rename_iranian_cit_code_1c3b38_idx_sage_city_code_8db749_idx_and_more'),
        ('persons', '0011_remove_personnel_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='birth_places',
            field=iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_places_personnel', to='iranian_cities.city', verbose_name='محل تولد'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='birth_certificate_issue_city',
            field=iranian_cities.fields.CityField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_certificate_issue_city_personnel', to='iranian_cities.city', verbose_name='محل صدور شناسنامه'),
        ),
    ]
