# Generated by Django 5.0.1 on 2025-01-25 11:40

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_personnel_birth_places_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('job_title', models.CharField(choices=[('expert', 'کارشناس'), ('senior_expert', 'کارشناس ارشد'), ('chief', 'رئیس'), ('deputy', 'معاون'), ('manager', 'مدیر'), ('ceo', 'مدیرعامل'), ('janitor', 'آبدارچی'), ('guard', 'نگهبان'), ('driver', 'راننده'), ('office_manager', 'مسئول دفتر'), ('intern', 'کارآموز')], max_length=50, verbose_name='عنوان شغلی')),
                ('work_experience', models.FloatField(verbose_name='میزان سابقه (سال)')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='از تاریخ')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('organizational_unit', models.CharField(choices=[('human_resources_management', 'مدیریت / معاونت سرمایه انسانی'), ('operations_support_management', 'مدیریت / معاونت عملیات و پشتیبانی'), ('it_management', 'مدیریت / معاونت فناوری اطلاعات'), ('business_management', 'مدیریت / معاونت کسب و کار'), ('planning_management', 'مدیریت / معاونت برنامه ریزی')], max_length=50, verbose_name='واحد سازمانی')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_histories', to='persons.personnel', verbose_name='پرسنل')),
            ],
            options={
                'verbose_name': 'سوابق شغلی',
                'verbose_name_plural': 'سوابق شغلی',
            },
        ),
    ]
