# Generated by Django 5.0.1 on 2025-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_employmenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationaldocument',
            name='name_doc',
            field=models.CharField(blank=True, choices=[('cycle', 'سیکل'), ('diploma', 'دیپلم'), ('associate', 'فوق دیپلم'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('doctorate', 'دکترا'), ('postdoctorate', 'فوق دکترا'), ('seminary', 'مدارک حوزوی')], default='diploma', max_length=50, null=True, verbose_name='نام مدرک تحصیلی'),
        ),
    ]
