# Generated by Django 5.0.1 on 2025-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_alter_educationaldocument_name_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Insurance_records',
            field=models.FloatField(verbose_name=' (سال) مجموع سوابق بیمه'),
        ),
    ]
