# Generated by Django 5.0.1 on 2025-01-29 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_alter_personnel_insurance_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='personnel',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
    ]
