# Generated by Django 5.0.1 on 2025-01-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_remove_personnel_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmenthistory',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='employmenthistory',
            name='start_date',
        ),
    ]
