# Generated by Django 5.0.1 on 2025-02-01 16:09

import persons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0018_remove_employmenthistory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/resume/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر رزومه'),
        ),
        migrations.AlterField(
            model_name='educationaldocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/educational/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='insurancerecords',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/training/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر  سابقه'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='identity_card_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/identity_card/', validators=[persons.models.validate_file_extension], verbose_name='تصویر یا فایل شناسنامه'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='national_card_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/national_card/', validators=[persons.models.validate_file_extension], verbose_name='تصویر یا فایل کارت ملی'),
        ),
        migrations.AlterField(
            model_name='trainingcertificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/training/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر گواهینامه آموزشی'),
        ),
    ]
