# Generated by Django 5.0.1 on 2025-02-02 09:51

import django.db.models.deletion
import django_jalali.db.models
import persons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0019_personnel_resume_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='identity_card_file',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='national_card_file',
        ),
        migrations.AddField(
            model_name='personnel',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره حساب بانک رفاه کارگران'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='card_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره کارت بانک رفاه کارگران'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='military_service_back',
            field=models.FileField(blank=True, null=True, upload_to='documents/military_service/', validators=[persons.models.validate_file_extension], verbose_name='پشت تصویر یا فایل کارت پایان خدمت'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='military_service_front',
            field=models.FileField(blank=True, null=True, upload_to='documents/military_service/', validators=[persons.models.validate_file_extension], verbose_name='روی تصویر یا فایل کارت پایان خدمت'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='national_card_file_back',
            field=models.FileField(blank=True, null=True, upload_to='documents/national_card/', validators=[persons.models.validate_file_extension], verbose_name='پشت تصویر یا فایل کارت ملی'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='national_card_file_front',
            field=models.FileField(blank=True, null=True, upload_to='documents/national_card/', validators=[persons.models.validate_file_extension], verbose_name='روی تصویر یا فایل کارت ملی'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='sheba_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شماره شبای بانک رفاه کارگران'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره بیمه'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='تلفن ثابت'),
        ),
        migrations.CreateModel(
            name='TypeDocRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name_type', models.CharField(blank=True, choices=[('identitycardfile', 'شناسنامه'), ('passport', 'گذرنامه')], max_length=100, null=True, verbose_name='نوع مدرک')),
                ('name_doc', models.CharField(blank=True, choices=[('firstpage', 'صفحه اول'), ('secondpage', 'صفحه دوم'), ('thirdpage', 'صفحه سوم'), ('fourthpage', 'صفحه چهارم'), ('fifthpage', 'صفحه پنجم')], max_length=100, null=True, verbose_name='نام صفحه')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='documents/typedoc/', validators=[persons.models.validate_file_extension], verbose_name='فایل یا تصویر  مدرک')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typedocs_records', to='persons.personnel', verbose_name='پرسنل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی\u200cکننده')),
            ],
            options={
                'verbose_name': 'مدرک شناسنامه/پاسپورت',
                'verbose_name_plural': 'مدارک شناسنامه/پاسپورت',
            },
        ),
    ]
