# Generated by Django 5.0.1 on 2025-02-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0020_remove_personnel_identity_card_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocrecords',
            name='serial_number',
            field=models.CharField(blank=True, help_text='د18/909090', max_length=20, null=True, verbose_name='شماره سریال'),
        ),
        migrations.AlterField(
            model_name='educationaldocument',
            name='name_doc',
            field=models.CharField(blank=True, choices=[('سیکل', 'سیکل'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا'), ('فوق دکترا', 'فوق دکترا'), ('مدارک حوزوی', 'مدارک حوزوی')], default='diploma', max_length=50, null=True, verbose_name='نام مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='job_title',
            field=models.CharField(choices=[('کارشناس', 'کارشناس'), ('کارشناس ارشد', 'کارشناس ارشد'), ('رئیس', 'رئیس'), ('معاون', 'معاون'), ('مدیر', 'مدیر'), ('مدیرعامل', 'مدیرعامل'), ('آبدارچی', 'آبدارچی'), ('نگهبان', 'نگهبان'), ('راننده', 'راننده'), ('مسئول دفتر', 'مسئول دفتر'), ('کارآموز', 'کارآموز')], max_length=50, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='organizational_unit',
            field=models.CharField(choices=[('مدیریت / معاونت سرمایه انسانی', 'مدیریت / معاونت سرمایه انسانی'), ('مدیریت / معاونت عملیات و پشتیبانی', 'مدیریت / معاونت عملیات و پشتیبانی'), ('مدیریت / معاونت فناوری اطلاعات', 'مدیریت / معاونت فناوری اطلاعات'), ('مدیریت / معاونت کسب و کار', 'مدیریت / معاونت کسب و کار'), ('مدیریت / معاونت برنامه ریزی', 'مدیریت / معاونت برنامه ریزی')], max_length=50, verbose_name='واحد سازمانی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='address',
            field=models.CharField(max_length=50, unique=True, verbose_name='محل سکونت'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='education_level',
            field=models.CharField(choices=[('سیکل', 'سیکل'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا'), ('فوق دکترا', 'فوق دکترا'), ('مدارک حوزوی', 'مدارک حوزوی')], default='diploma', max_length=50, verbose_name='میزان تحصیلی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='employment_status',
            field=models.CharField(choices=[('تمام وقت', 'تمام وقت'), ('پاره وقت', 'پاره وقت'), ('ساعتی', 'ساعتی'), ('مشاور', 'مشاور'), ('قطع همکاری', 'قطع همکاری')], default='full_time', max_length=20, verbose_name='وضعیت کارمند'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='hair_color',
            field=models.CharField(choices=[('قهوه ای', 'قهوه ای'), ('مشکی', 'مشکی'), ('سفید', 'سفید'), ('بلوند', 'بلوند'), ('سایر', 'سایر')], default='brown', max_length=20, verbose_name='رنگ مو'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='home_owner',
            field=models.CharField(choices=[('مالک', 'مالک'), ('مستاجر', 'مستاجر'), ('خانه پدری', 'خانه پدری')], default='owner', max_length=20, verbose_name='نوع تملک'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='job_title',
            field=models.CharField(choices=[('کارشناس', 'کارشناس'), ('کارشناس ارشد', 'کارشناس ارشد'), ('رئیس', 'رئیس'), ('معاون', 'معاون'), ('مدیر', 'مدیر'), ('مدیرعامل', 'مدیرعامل'), ('آبدارچی', 'آبدارچی'), ('نگهبان', 'نگهبان'), ('راننده', 'راننده'), ('مسئول دفتر', 'مسئول دفتر'), ('کارآموز', 'کارآموز')], default='expert', max_length=20, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='marital_status',
            field=models.CharField(choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل'), ('سایر', 'سایر')], default='single', max_length=20, verbose_name='وضعیت تاهل'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='military_service',
            field=models.CharField(choices=[('انجام شده', 'انجام شده'), ('انجام نشده', 'انجام نشده'), ('معافیت پزشکی', 'معافیت پزشکی'), ('معافیت غیرپزشکی', 'معافیت غیرپزشکی'), ('در حال انجام', 'در حال انجام'), ('سایر', 'سایر')], default='done', max_length=40, verbose_name='وضعیت خدمت سربازی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nationality',
            field=models.CharField(choices=[('ایرانی', 'ایرانی'), ('غیر ایرانی', 'غیر ایرانی')], default='iranian', max_length=20, verbose_name='ملیت'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='organizational_title',
            field=models.CharField(choices=[('کارشناس', 'کارشناس'), ('کارشناس ارشد', 'کارشناس ارشد'), ('رئیس', 'رئیس'), ('معاون', 'معاون'), ('مدیر', 'مدیر'), ('مدیرعامل', 'مدیرعامل'), ('آبدارچی', 'آبدارچی'), ('نگهبان', 'نگهبان'), ('راننده', 'راننده'), ('مسئول دفتر', 'مسئول دفتر'), ('کارآموز', 'کارآموز')], default='expert', max_length=50, verbose_name='عنوان سازمانی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='organizational_unit',
            field=models.CharField(choices=[('مدیریت / معاونت سرمایه انسانی', 'مدیریت / معاونت سرمایه انسانی'), ('مدیریت / معاونت عملیات و پشتیبانی', 'مدیریت / معاونت عملیات و پشتیبانی'), ('مدیریت / معاونت فناوری اطلاعات', 'مدیریت / معاونت فناوری اطلاعات'), ('مدیریت / معاونت کسب و کار', 'مدیریت / معاونت کسب و کار'), ('مدیریت / معاونت برنامه ریزی', 'مدیریت / معاونت برنامه ریزی')], default='human_resources_management', max_length=50, verbose_name='واحد سازمانی'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='religion',
            field=models.CharField(choices=[('اسلام', 'اسلام'), ('مسیحیت', 'مسیحیت'), ('زرتشت', 'زرتشت'), ('یهودیت', 'یهودیت'), ('سایر', 'سایر')], default='islam', max_length=20, verbose_name='دین'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sect',
            field=models.CharField(choices=[('سنتی', 'سنتی'), ('شیعه', 'شیعه')], default='shia', max_length=20, verbose_name='مذهب'),
        ),
    ]
