# Generated by Django 5.0.1 on 2025-02-02 10:58

import persons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0021_typedocrecords_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='owner_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/owner/', validators=[persons.models.validate_file_extension], verbose_name='تصویر یا فایل سند/اجاره نامه'),
        ),
    ]
