# Generated by Django 5.0.1 on 2025-02-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0022_personnel_owner_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnel',
            old_name='national_id',
            new_name='NATIONALID',
        ),
    ]
