# Generated by Django 5.0.1 on 2025-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0023_rename_national_id_personnel_nationalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='callphone',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='sect',
            field=models.CharField(choices=[('سنی', 'سنی'), ('شیعه', 'شیعه')], default='shia', max_length=20, verbose_name='مذهب'),
        ),
    ]
