# Generated by Django 5.0.1 on 2025-02-02 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0024_alter_personnel_callphone_alter_personnel_sect'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ فعال\u200cسازی')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
        ),
        migrations.AlterField(
            model_name='personnel',
            name='education_level',
            field=models.CharField(choices=[('سیکل', 'سیکل'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا'), ('فوق دکترا', 'فوق دکترا'), ('مدارک حوزوی', 'مدارک حوزوی')], default='diploma', max_length=50, verbose_name='میزان تحصلات'),
        ),
    ]
