# Generated by Django 5.0.1 on 2025-02-03 09:49

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0025_license_alter_personnel_education_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کالا')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت (ریال)')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='AssetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شماره سریال')),
                ('receive_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دریافت')),
                ('return_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.asset', verbose_name='نام کالا')),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assets', to=settings.AUTH_USER_MODEL, verbose_name='شخص تحویل\u200cدهنده')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assets', to=settings.AUTH_USER_MODEL, verbose_name='شخص تحویل گیرنده')),
            ],
            options={
                'verbose_name': 'معامله دارایی',
                'verbose_name_plural': 'معاملات دارایی',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.brand', verbose_name='برند کالا'),
        ),
    ]
