# Generated by Django 5.0.1 on 2025-02-03 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0026_asset_brand_assettransaction_asset_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransaction',
            name='accesories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesories', to='persons.asset', verbose_name='لوازم جانبی'),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='persons.asset', verbose_name='نام کالا'),
        ),
    ]
