# Generated by Django 5.0.1 on 2025-02-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0027_assettransaction_accesories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='name_asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='نام کالا')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.name_asset', verbose_name='نام کالا'),
        ),
    ]
