# Generated by Django 5.0.1 on 2025-02-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0028_name_asset_alter_asset_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name_asset',
            new_name='NameAsset',
        ),
    ]
