# Generated by Django 5.0.1 on 2025-02-03 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0030_alter_nameasset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettransaction',
            name='accesories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.nameasset', verbose_name='لوازم جانبی'),
        ),
    ]
