# Generated by Django 5.0.1 on 2025-02-03 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0031_alter_assettransaction_accesories'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransaction',
            name='previous_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_transactions', to='persons.assettransaction', verbose_name='تراکنش قبلی'),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='accesories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.nameasset', verbose_name='لوازم جانبی'),
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شماره پلاک'),
        ),
    ]
