# Generated by Django 5.0.1 on 2025-02-03 11:12

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0032_assettransaction_previous_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assettransaction',
            name='previous_transaction',
        ),
        migrations.CreateModel(
            name='AssetTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_date', django_jalali.db.models.jDateField(verbose_name='تاریخ دریافت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('asset_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='persons.assettransaction', verbose_name='تراکنش اصلی')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assets_history', to=settings.AUTH_USER_MODEL, verbose_name='شخص تحویل گیرنده')),
            ],
            options={
                'verbose_name': 'تاریخچه معامله دارایی',
                'verbose_name_plural': 'تاریخچه معاملات دارایی',
            },
        ),
    ]
