# Generated by Django 5.0.1 on 2025-02-03 11:55

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0033_remove_assettransaction_previous_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransactionhistory',
            name='giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_assets_history', to=settings.AUTH_USER_MODEL, verbose_name='شخص تحویل\u200cدهنده'),
        ),
        migrations.AddField(
            model_name='assettransactionhistory',
            name='return_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AlterField(
            model_name='assettransactionhistory',
            name='receive_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ دریافت'),
        ),
        migrations.AlterField(
            model_name='assettransactionhistory',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_assets_history', to=settings.AUTH_USER_MODEL, verbose_name='شخص تحویل گیرنده'),
        ),
    ]
