# Generated by Django 5.0.1 on 2025-02-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0034_assettransactionhistory_giver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت (ریال)'),
        ),
    ]
