# Generated by Django 5.0.1 on 2025-02-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0035_alter_asset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransaction',
            name='approval_status',
            field=models.TextField(blank=True, null=True, verbose_name='وضعیت تأیید'),
        ),
        migrations.AddField(
            model_name='assettransaction',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تأیید شده'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='work_experience',
            field=models.FloatField(verbose_name='میزان سابقه (ماه)'),
        ),
    ]
