# Generated by Django 5.0.1 on 2025-02-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0036_assettransaction_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('department_code', models.CharField(max_length=10, verbose_name='کد دپارتمان')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='assettransaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assets', to=settings.AUTH_USER_MODEL, verbose_name='شخص گیرنده'),
        ),
        migrations.AlterField(
            model_name='assettransactionhistory',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_assets_history', to=settings.AUTH_USER_MODEL, verbose_name='شخص گیرنده'),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='شماره اتاق')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.departments', verbose_name='دپارتمان')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
            },
        ),
    ]
