# Generated by Django 5.0.1 on 2025-02-05 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0037_departments_alter_assettransaction_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.rooms', verbose_name='موقعیت مکانی کالا'),
        ),
    ]
