# Generated by Django 5.0.1 on 2025-02-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0038_assettransaction_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True, verbose_name='نام جدول')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام ستون')),
                ('type', models.CharField(choices=[('VARCHAR(255)', 'متن (VARCHAR)'), ('INTEGER', 'عدد صحیح (INTEGER)'), ('FLOAT', 'عدد اعشاری (FLOAT)'), ('BOOLEAN', 'منطقی (BOOLEAN)'), ('TIMESTAMP', 'تاریخ و زمان (TIMESTAMP)')], max_length=50, verbose_name='نوع داده')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='persons.customtable')),
            ],
        ),
    ]
